export const greetings = [
  "Howdy from USA!",
  "¡Hola from Spain!",
  "Bonjour from France!",
  "Hallo from Germany!",
  "Ciao from Italy!",
  "Olá from Portugal!",
  "你好 from China!",
  "こんにちは from Japan!",
  "안녕하세요 from Korea!",
  "Привет from Russia!",
  "مرحبا from the Middle East!",
  "नमस्ते from India!",
  "Merhaba from Turkey!",
  "Hallo from the Netherlands!",
  "Γειά σου from Greece!",
  "שלום from Israel!",
  "Hej from Sweden!",
  "Cześć from Poland!",
  "Xin chào from Vietnam!",
  "สวัสดี from Thailand!",
];
